<h2>Do NOT edit this email!</h2>

This Email will always be sent to the Trustpilot Automatic Feedback 1-Click Service. <br />
<br />
The Trustpilot Automatic Feedback Service will automatically send an Email to your Customer with a request to rate your service.<br />
<br />
<h2>How does it work?</h2>
<ol>
<li>Trustpilot provides you with a unique Automatic Feedback Service email address, which we host for you on a secure, neutral server. 
 
<li>When a customer makes a purchase from your website, your website admin system sends  a copy of the order confirmation email to your unique Trustpilot email address. 

<li>When our system receives this email, it automatically extracts the key information (customer email, order ID, name) and creates a review invitation email. 
 
<li>After a set number of days (you decide how many), the system sends this email to the customer. It  will send out the review email from your order e-mail address, as if it has come directly from you.  

<li>The customer receives the email and clicks on the unique link which takes them directly to the ‘one-click’ review page.  

<li>The link identifies them to Trustpilot so they do not need to enter personal information or confirm 
their email address. As soon as they press ‘Submit’, the review goes live. 
 
<li>The feedback system has multi-language recognition, so a French order confirmation triggers a 
French template and a French version of Trustpilot etc. 

</ol>

Benefits of the 1-Click Service:<br />
<ol>
<li>your customers do only need to enter their rating - all other data is already know at Trustpilot
<li>3-10 times more ratings compared to direct emails
</ol>
<br />
<blockquote><a href="http://download.trustpilot.dk/B2B/TP%20Automatic%20Feedback%20Service.The%20Guide_EN.pdf"><b>Download TP Automatic Feedback Service Guide (EN).PDF</b></a></blockquote>
<br />
<br />
<br />


<hr noshade size="1">

name: {$firstname} {$lastname}<br />
<br />
<hr noshade size="1">
email: {$customers_email_address}<br />
order_id: {$order_id}<br />
order_date: {$order_date}<br />
status_date: {$status_date}<br />
<br />
TP_LANG: {$language}<br />
TP_DELAY: 0<br>

TP_CUSTOM1: {$tp_block_url}

<br />
<br />
generated by Trustpilot MailBeez<br>
http://www.mailbeez.com/documentation/trustpilot<br>
TP_AFFILIATE: MailBeez