Do NOT edit this email!

Read HTML Version for more Info

Trustpilot Trigger Email

name: {$firstname} {$lastname}
email: {$customers_email_address}
order_id: {$order_id}
order_date: {$order_date}
status_date: {$status_date}

TP_LANG: {$language}
TP_DELAY: 0 

TP_CUSTOM1: {$tp_block_url}


generated by Trustpilot MailBeez
http://www.mailbeez.com/documentation/trustpilot
TP_AFFILIATE: MailBeez
