--
-- Script was generated by mommaroodles
-- Product home page: http://webwolf.co.za
-- Script date 13/08/14 07:56:57 PM
-- Server version: 5.6.12-log
--


CREATE TABLE coupon_email_track (
  unique_id int(11) NOT NULL AUTO_INCREMENT,
  coupon_id int(11) NOT NULL DEFAULT 0,
  customer_id_sent int(11) NOT NULL DEFAULT 0,
  sent_firstname varchar(32) DEFAULT NULL,
  sent_lastname varchar(32) DEFAULT NULL,
  emailed_to varchar(32) DEFAULT NULL,
  date_sent date NOT NULL DEFAULT '0000-00-00',
  PRIMARY KEY (unique_id)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_unicode_ci;

CREATE TABLE coupon_gv_customer (
  customer_id int(5) NOT NULL DEFAULT 0,
  amount decimal(8, 2) UNSIGNED NOT NULL DEFAULT 0.00,
  PRIMARY KEY (customer_id),
  INDEX customer_id (customer_id)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_unicode_ci;

CREATE TABLE coupon_gv_queue (
  unique_id int(5) NOT NULL AUTO_INCREMENT,
  customer_id int(5) NOT NULL DEFAULT 0,
  order_id int(5) NOT NULL DEFAULT 0,
  amount decimal(8, 2) UNSIGNED NOT NULL DEFAULT 0.00,
  date_created date NOT NULL DEFAULT '0000-00-00',
  ipaddr varchar(32) NOT NULL DEFAULT '',
  release_flag char(1) NOT NULL DEFAULT 'N',
  PRIMARY KEY (unique_id),
  INDEX uid (unique_id, customer_id, order_id)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_unicode_ci;

CREATE TABLE coupon_redeem_track (
  unique_id int(11) NOT NULL AUTO_INCREMENT,
  coupon_id int(11) NOT NULL DEFAULT 0,
  customer_id int(11) NOT NULL DEFAULT 0,
  redeem_date date NOT NULL DEFAULT '0000-00-00',
  redeem_ip binary(20) NOT NULL,
  order_id int(11) NOT NULL DEFAULT 0,
  PRIMARY KEY (unique_id, coupon_id, customer_id)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_unicode_ci;

CREATE TABLE coupons (
  coupon_id int(11) NOT NULL AUTO_INCREMENT,
  coupon_type char(1) NOT NULL DEFAULT 'F',
  coupon_code varchar(32) NOT NULL DEFAULT '',
  coupon_amount decimal(8, 2) UNSIGNED NOT NULL DEFAULT 0.00,
  coupon_minimum_order decimal(8, 2) UNSIGNED NOT NULL DEFAULT 0.00,
  coupon_start_date date DEFAULT '0000-00-00',
  coupon_expire_date date DEFAULT '0000-00-00',
  uses_per_coupon int(5) NOT NULL DEFAULT 1,
  uses_per_user int(5) NOT NULL DEFAULT 0,
  restrict_to_products varchar(255) DEFAULT NULL,
  restrict_to_categories varchar(255) DEFAULT NULL,
  restrict_to_customers text DEFAULT NULL,
  coupon_active char(1) NOT NULL DEFAULT 'Y',
  coupon_status int(1) NOT NULL DEFAULT 1,
  date_created date NOT NULL DEFAULT '0000-00-00',
  date_modified date NOT NULL DEFAULT '0000-00-00',
  PRIMARY KEY (coupon_id)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_unicode_ci;

CREATE TABLE coupons_description (
  coupon_id int(11) NOT NULL DEFAULT 0,
  language_id int(11) NOT NULL DEFAULT 0,
  coupon_name varchar(32) NOT NULL DEFAULT '',
  coupon_description text DEFAULT NULL,
  PRIMARY KEY (language_id, coupon_id)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_unicode_ci;

INSERT INTO configuration_group(configuration_group_id, configuration_group_title, configuration_group_description, sort_order, visible) VALUES
(100, 'CCGV Settings', 'Discount Coupons and Gift Voucher Settings', 100, 1);

INSERT INTO configuration (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, last_modified, date_added, use_function, set_function)
  VALUES ('Welcome Gift Voucher Amount', 'NEW_SIGNUP_GIFT_VOUCHER_AMOUNT', '0', 'Welcome Gift Voucher Amount: If you do not wish to send a Gift Voucher in your create account email put 0 for no amount else if you do place the amount here i.e. 10.00 or 50.00 no currency signs', 100, 1, NULL, '2003-12-05 05:01:41', NULL, NULL);
INSERT INTO configuration (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, last_modified, date_added, use_function, set_function)
  VALUES ('Welcome Discount Coupon Code', 'NEW_SIGNUP_DISCOUNT_COUPON', '', 'Welcome Discount Coupon Code: if you do not want to send a coupon in your create account email leave blank else place the coupon code you wish to use', 100, 2, NULL, '2003-12-05 05:01:41', NULL, NULL);
INSERT INTO configuration (configuration_title, configuration_key, configuration_value, configuration_description, configuration_group_id, sort_order, last_modified, date_added, use_function, set_function)
  VALUES ('Coupon Code Length', 'CCGV_SECURITY_CODE_LENGTH', '8', 'Coupon Code Length: Set the length of the auto generated coupon code', 10, 3, NULL, '2014-12-05 05:01:41', NULL, NULL);

